import type { Metadata } from "next";
import { Inter, Sansita_Swashed } from "next/font/google";
import "./globals.css";
import SupabaseProvider from "@/providers/supabase-context";

const font= Sansita_Swashed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SUPA APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SupabaseProvider>
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
